CREATE DATABASE  BANK;
USE BANK;

DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
    ac_no INT NOT NULL AUTO_INCREMENT,
    cname VARCHAR(45) NOT NULL UNIQUE,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 1000.00,
    pass_code VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ac_no)
);
DESCRIBE customer;
